services:
  foghorn:
    image: ghcr.io/pfarrer/foghorn:latest
    container_name: foghorn
    user: root
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.yml:/app/config.yml:ro
    environment:
      - TZ=UTC
    command: ["-c", "/app/config.yml"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
