services:
  foghorn:
    image: ghcr.io/pfarrer/foghorn:latest
    container_name: foghorn
    user: root
    restart: unless-stopped
    ports:
      - "7676:7676"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./example.yaml:/app/example.yaml:ro
    environment:
      - TZ=UTC
    command: ["-c", "/app/example.yaml", "--status-listen", "0.0.0.0:7676"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
